BlenderKit/BlenderKit

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

PR adds forms for BUG and FEATURE reports.
@vilemduha and @PetrDlouhy please take a look if the forms asks for enough information. Maybe for the environment we need more than Blender version, addon version and OS? For the logs - should we provide more detailed info how to get them? Let me know your suggestions, I will add them to the PR.

Init bug and feature forms

---

requirements.txt

Issue #69 Add certifi to requirements.txt

---

__init__.py
daemon/assets.py
timer.py
ui_panels.py
utils.py

Fix unpacking being blocked by Megascans and increase addon version to 3.1.2

Unpack fix

---

daemon_lib.py

Daemon log should use global files directory

---

__init__.py

Fixes #104 
On registration it overrides default removal button with custom removal button - this button behaves the same for all other add-ons, but in case of blenderkit it differs: it first moves the addon to blenderkit_data/.trash/randomhex, then tries to delete the .thrash directory without failing on errors. Any blocked .pyd files will stay in the trash directory.
It does not un-register the button because we need custom removal even in situations when blenderkit was started and disabled - the daemon will still run (or its leftover - zombie process) and the daemon will still have the files open. So we keep the custom button registered so custom removal will happen.
**verified on Windows 10**
- FIX: uninstall is not blocked by daemon anymore
- uninstall of other add-ons is not …

Override Blender remove button

---

asset_bar_op.py
search.py

update tooltip thumbnail when it finishes downloading

---

daemon_lib.py

fixes #136
fixes #127 
fixes #95

Add blender.crt/vcruntime140.dll on Windows to daemon's PATH, add check if Python interpreter is ready

---

asset_bar_op.py
bkit_oauth.py
search.py
timer.py

Fix results switching

---

bkit_oauth.py

Save preferences immediately after login/logout

---

bkit_oauth.py
comments_utils.py
utils.py

Fixes 166#
also don't send notification requests when user isn't logged in.

Save blender prefs when save_prefs is called

---

daemon_lib.py

fixes #21 
First place where write permissions to global_dir are used is when daemon creates log for its reports. Thus I have created a check on the result and if daemon log file creation throws an error, it prints out a red report in the Blender GUI. I am not adding more checks as the creation of daemon log is precondition for everything else. If that creation goes well, then we can take as granted that global_dir is writable.

Improve error report for permissionError to global_dir

---

bkit_oauth.py
daemon/oauth.py

Fix successful login being handled as failed

---

__init__.py
utils.py

Save model, material, hdr max resolution in userprefs

---

daemon_lib.py

Catch error OSError: [WinError 87] when daemon starts

---

bkit_oauth.py
ui_panels.py
utils.py

Search header placement fixed when tool header is hidden,
several more small UI fixes.

Fix search header

---

ui_panels.py

Show comments to all users, not only validators.
also do the same with generated resolutions property

Show comments to all users

---

download.py
image_utils.py
resolutions.py
ui.py
ui_panels.py

Various fixes for resolutions not working in 3.1.5 and for generation of resolutions.
Still planning to:
- support resolutions switching for packed files (for release)
- remove resolutions generating code from the addon (can be added after release)

Resolutions fixes

---

ratings.py

Remove target propertis from rating gizmo

---

__init__.py
download.py
ui_panels.py

This enables saving this preference for users.
further, explain unpacking to pre-fix the resolution swapping for users

Move resolution to preferenes

---

daemon/oauth.py

Fix broken daemon in Blender 3.0

---

asset_bar_op.py

Invites the user to drag-drop by changing the cursor to HAND value.

Swap mouse cursor to hand when over assets.

---

comments_utils.py
ui_panels.py

also add a 'see online' button to asset card to reach easier the webpage of the asset.

use comments api in /api/v1

---

__init__.py
append_link.py
asset_bar_op.py
asset_inspector.py
autothumb.py
autothumb_material_bg.py
bg_blender.py
bkit_oauth.py
categories.py
comments_utils.py
daemon_lib.py
dependencies.py
download.py
log.py
paths.py
ratings.py
ratings_utils.py
reports.py
search.py

- adds formatting to logging, so we see from which file and which line and when the message comes (huge improvement over using prints)
- (we can later add support to log into file)
- adds report to GUI that daemon is running
- logging now logs all GUI messages to users
- converted some prints to logging via bk_logger object (we can set its level to DEBUG if we need to catch even smallest problems - however there are not many DEBUGS logs right now)
- removed some unused prints - those which were commented out

improve logging

---

asset_bar_op.py
comments_utils.py
ui_panels.py

Comments - add Private switch and disable used flags (like/dislike)
The feedback on all switches is now immediate.

Comments validation

---

utils.py

(cherry picked from commit c9c431e4bd0da2e5940ebe65520fae8cbd2fc7d4)

Fix scale - was inverted too.

---

__init__.py
search.py

fix #269 
remove also  useless 'search_error' property

fix #269 : Log out after with invalid token search

---

.github/workflows/PR.yml

Update testing versions

---

daemon/daemon.py
daemon_lib.py
dependencies.py
global_vars.py
timer.py

Improve daemon error reports, cover OSError 10013

---

search.py

Do not reset texture Limit Size

---

asset_bar_op.py
bl_ui_widgets/bl_ui_draw_op.py
disclaimer_op.py
download.py
search.py
ui.py
utils.py

cleanup some unused old code too

fix pointer to areas in the ui code and cleanup

---

daemon/daemon.py

Make sslcontext.load_default_certs optional

---

__init__.py
download.py
ui.py
ui_panels.py

Prevent brush download if not at sculpt or paint

---

daemon_lib.py

Remove daemon startup message from GUI

---

__init__.py
log.py

Init logging into file

---

daemon/daemon.py
daemon/disclaimer.py
daemon/search.py
daemon/tasks.py

Handle exceptions in the ensure_future()

---

ratings.py
ui_panels.py

Disable ratings for locked assets

---

bkit_oauth.py
categories.py
search.py
timer.py

Fetch categories on scene load

---

log.py
reports.py

Log correct file and line in add_report() and log.py

---

append_link.py
resolutions.py

Fix resolutions upload
and also fix a stupid bug in appending same name assets.

Fix resolutions

---

timer.py

Do not get profile when user is not logged in

---

append_link.py
download.py

fixes #359 
Tested on Windows 10 with Blender 3.3.1, 3.4.0 and 3.5.0.

Fix slashes in call to bpy.ops.wm.append()

---

.github/make-tests-matrix.py
.github/workflows/PR.yml
.github/workflows/master-push.yml
.github/workflows/nightly.yml

 Load Blender nightly build URLs dynamically

---

daemon/globals.py
daemon/oauth.py
global_vars.py

code_verifier not present in daemon globals in some cases

---

daemon/daemon.py
daemon/globals.py
daemon_lib.py

Set online_status_check to new endpoint

---

daemon/disclaimer.py
daemon/oauth.py
daemon/search.py
daemon_lib.py

Handle API limit exceeded error

---

autothumb_material_bg.py
resolutions.py

udim unpacking
autothumb for materials had wrong import, wonder for how many versions this was not working ;)

Fix 2 problems

---

CONTRIBUTING.md
__init__.py
disclaimer_op.py
global_vars.py

add server var to various links to website (won't work for devel usually, but that's intentional for testing) add a tip for users so they can switch on pre-releases

Set server address directly through env variable

---

__init__.py
search.py

fix too many search updates when using sliders in the UI

---

disclaimer_op.py

use time.time() for starting fade out, instead of counting timer runs

fix #297 disclaimer timer

---

download.py

fixes #417 
this handles the error with an appropriate report

fix #417 - asset has no files

---

ui_panels.py

fix #220 alignment of UI elements

---

autothumb.py
categories.py
daemon/uploads.py
download.py
reports.py
timer.py
ui_panels.py
upload.py

Force category when uploading
fix handling of upload of scenes and HDRs
improve checking for upload thumbnail
improve reporting and fix it (wasn't reported to user) fix an occasional bug in reports (in case of no area to report in) cleanup

Uploads polishing

---

search.py

fixes #342 
free_first needed to be put in query instead of params of search to be recorded in history and taken as difference - so the search is updated.

fix #342 free first filter

---

ui_panels.py

fizes #432 
makes inteface cleaner when animating.

Hide search UI when overlays are hidden

---

ui.py

fixes #319 
this needs a bit of testing for various cases, but generally should check hopefully more variants of how objects can be hidden from viewport. tested in blender 3.4.1

fix #319 respect localmode when raycasting

---

__init__.py
bkit_oauth.py
daemon/daemon.py
daemon_lib.py
global_vars.py
timer.py

Daemon and add-on try more ports if needed

---

__init__.py

For beta set version to 3.4.0.230116, update docs URL

---

search.py

Issue #463 - first search fails on query['free_first']

---

__init__.py
bkit_oauth.py
global_vars.py
paths.py
rerequests.py

Reset global_vars on every registration

---

daemon/assets.py

Fail get download URL as soon as error occurs

---

reports.py

Add file and lineno into red GUI reports

---

daemon/daemon.py

Log daemon PID on start

---

daemon/daemon.py

fixes #468 
pls merge after #472

Allow daemon to reuse addr of socket to not fail the start when it is not necessary

---

__init__.py
autothumb.py
ui_panels.py

fix #452 UI inconsistencies

---

__init__.py
addon_updater.py
addon_updater_ops.py

fixes #479 
If prereleases are enabled in prefs - check for updates on each start

Show prereleases ASAP

---

__init__.py
search.py
ui_panels.py

this was quite simple, the question is if this kind of placement is the best, if it shouldnt' be category-> by modifier. could also search simulations, and rigged stuff.

Add geometry nodes filter

---

daemon/assets.py
daemon/utils.py
download.py
timer.py

#440 - Report too long filepath correctly

---

disclaimer_op.py

now correctly opens relative paths

Fix embarrassing bug in disclaimer

---

__init__.py
ui_panels.py

fixes #507 
- remove unused methods in LogoStatus class
- add check for daemon status into scene_load
- turn logo into color if daemon is ok

#507 Keep logo colored on scene load if daemon runs

---

.github/make-tests-matrix.py
.github/workflows/PR.yml

#482 Cache Blender binaries in Github actions

---

.github/workflows/PR.yml
.github/workflows/master-push.yml
.github/workflows/nightly.yml

#482 Add caching also to nightly and master-push actions

---

ratings_utils.py

we need to do a quick re-release,

Fix rating where accidentaly quality was sent instead of complexity

---

daemon_lib.py

Add-on to daemon connection should ignore system proxy

---

asset_bar_op.py
bl_ui_widgets/bl_ui_button.py
daemon/daemon.py
daemon/ratings.py
daemon_lib.py
ratings.py
ratings_utils.py
search.py
timer.py
utils.py

Polish bookmarks

---

disclaimer_op.py

fixes #491 
Add-on was hiding tips only when daemon was not working. This PR skips the tips if they are not enabled as it should be.
The online tips however will be shown. This is important because sometimes we need to inform the users ASAP and onlince disclaimer popup is the best way. We should limit the number of messages on the server side.

#491 - Fix spamming tips

---

append_link.py
asset_bar_op.py
daemon/assets.py
daemon/ratings.py
download.py
search.py
timer.py
ui.py

This fixes following
pending tasks (if user e.g. switches to edit mode durning download, it should wait till he switches back to ob mode)
Fix progress bars in asset bar - these were really quite broken
Brushes picking switch to sculpt mode and layout automagically
rename update_images to update_buttons in asset bar
remove forgotten bookmark printouts

Download fixes

---

asset_bar_op.py
search.py

Minor polishing fixes I forgot to commit after merge of the asset bar improvemnts
progress bars were now double updated
Use event timer and timed updates from asset bar(instead of modal runs counter)

Minor asset bar fixes post merge

---

daemon/daemon.py
daemon/uploads.py
daemon/utils.py
daemon_lib.py
timer.py

fixes #569 
- makes DNS check asynchronous, so it does not block daemon
- non-blocked daemon then does not report slowly when offline which forced add-on to start a new daemon
- on quite shitty network it takes daemon 0.00546s - 0.01353s to report, so quite fast and DNS check is faster then before

#569 - Make the DNS check asynchronous

---

daemon/daemon.py
daemon/uploads.py

fixes #572 
Adds new sppecialized daemon conector and session for uploads
Increases timeout for upload and download aiohttp sessions to 1 hour from 5 minutes
Logs a little bit more the progress of upload into daemon log

#572 - Increase timeout for uploads and downloads

---

upload.py

fiixes #600 
lets call about this PR on Tuesday or Wednesday

#600 Missing assetBaseId and Id on re-upload

---

asset_bar_op.py
daemon/disclaimer.py

add hover color to the bookmark button

use api token when retrieving disclaimer

---

daemon/assets.py
daemon/uploads.py

#609 Print stdout and stderr when un/packing fails

---

ratings_utils.py
ui_panels.py

value of 0 isn't used and is as a placeholder for default value, now is shown as - instead of 0

Tiny fix to rating complexity UI

---

__init__.py

#604 Mention in preferences that HTTPS proxies are not supported

---

__init__.py

#612 Put sys.stdout.reconfigure() into try-except

---

daemon/daemon.py
daemon/daemon_configurator.py
daemon/daemon_globals.py
daemon/daemon_utils.py
daemon_lib.py
global_vars.py
timer.py
ui_panels.py

- remove online check from daemon, because it was blocked by some antiviruses
- rename DAEMON_ONLINE to DAEMON_RUNNING
- disable GUI only when daemon is not running - responding with results
should fix: #631, #633
confirmed: https://github.com/BlenderKit/blenderkit/issues/631#issuecomment-1521850350

#631 Remove online check, use DAEMON_RUNNING

---

daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_comments.py
daemon/daemon_disclaimer.py
daemon/daemon_oauth.py
daemon/daemon_profiles.py
daemon/daemon_ratings.py
daemon/daemon_search.py
daemon/daemon_uploads.py
daemon/daemon_utils.py

Add raise_for_status to all session in Daemon

---

asset_bar_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_drag_panel.py
bl_ui_widgets/bl_ui_image.py
bl_ui_widgets/bl_ui_label.py
search.py
timer.py
ui.py

fixes #644 
- when thumbnail download tasks is reported with ERROR - thumbnail not available icon is set
- changes star * imports to explicit imports

#644 Set thumbnail not available on thumb error

---

daemon/daemon_utils.py

#664 Check that resp_text is not None in extract_error_message

---

__init__.py
ui_panels.py
upload.py

#662 Improve upload UI

---

daemon/daemon_tasks.py
reports.py

#666 Daemon now reports file and lineno of error

---

daemon/daemon_ratings.py

#658 Do not convert delete rating response into JSON

---

autothumb.py
bg_blender.py
ui_panels.py

#679 Catch end of thumbnail render properly

---

ratings.py
ratings_utils.py

#678 Do not send DELETE rating when local rating is None or already 0

---

CONTRIBUTING.md
daemon/daemon.py
dev.py

#428 Add compilation for daemon

---

__init__.py
append_link.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_draw_op.py
bl_ui_widgets/bl_ui_label.py
disclaimer_op.py
tasks_queue.py
ui.py

Hopefully fix context in blender 4.0 and also blf

---

search.py
timer.py

#707 Logout on Invalid token error, show informative message

---

ui_panels.py
upload.py

#661 Private uploads do not require category filled in

---

daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_comments.py
daemon/daemon_configurator.py
daemon/daemon_disclaimer.py
daemon/daemon_oauth.py
daemon/daemon_profiles.py
daemon/daemon_ratings.py
daemon/daemon_search.py
daemon/daemon_uploads.py
daemon/daemon_utils.py
log.py

fixes #719 
- replace temporary tokens with 3 asterisks in the logs
- replace permanent tokens with 5 asterisks in the logs
- works for logs in add-on as well in the daemon

#719 Mask tokens in log messages

---

asset_bar_op.py
ui_panels.py
utils.py

fixes #744
- show exact version bellow bigger asset preview
- show slightly different messages for major, minor or patch difference

#744 Show exact version for assets from higher Blender versions

---

log.py

fixes #750 
- remove setting logging level for whole logging module
- adding logging level to bk_logger

#750 Set logging level for bk_logger explicitly

---

__init__.py
daemon/daemon.py

INVESTIGATION for #647
- adds option to disable the SSL checks in the preferences
- informs users that this option is not safe

#742 Allow to disable SSL checks in preferences->SSL Context:DISABLED

---

ui.py

fix #761  
until now it switched correctly to sculpt mode, but didn't load the brush.

Fix #761 Append brush when switching to sculpt mode

---

tasks_queue.py

fixes #794 
- quality and working_hours called same function, which caused second rating to delete the first in stashed dict
- now adds rating type to stashed key, so both ratings are kept

#794 Fix when quality and working hours are clicked fastly

---

__init__.py
bkit_oauth.py
global_vars.py
ui_panels.py

fixes #797
- adds link into tips
- adds button into preferences

#797 Add BlenderKit Community Discord link into add-on

---

.github/workflows/PR.yml
.github/workflows/main-push.yml
.github/workflows/release.yml
.gitignore
CONTRIBUTING.md
daemon/daemon.py
daemon/daemon_globals.py
dev.py

fixes #799
- moving from Nuitka to pyinstaller
- adds builds to PRs, main-push, release
- available for devs in `python dev.py compile`

#799 Add automated daemon builds

---

__init__.py
search.py
ui_panels.py

needed to fix a accute situtation - some ratings by validators didn't go through

add unrated complexity for validators

---

.github/make-tests-matrix.py

#812 Update Blender versions in automated tests

---

ui_panels.py

was annoying not to have it there sometimes.

enable asset bar in pose mode

---

autothumb.py
upload.py

+fix a small bug when fetching texture in upload panel.

Fix metadata edit categories

---

search.py

#825 Fix bad results after category is unset

---

asset_bar_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py
image_utils.py
search.py
ui.py
utils.py

fixes #552 
Ready for review, tested with 4.0.0-alpha and 3.0.1. In both works well. The thumbnails are still little bit bright, but not oversaturated and overexposed as before.

#552 Guess colorspace for sRGB or ACES

---

daemon/daemon.py
daemon/daemon_oauth.py

#846 Fix debug print when SSL is disabled

---

ui_panels.py

#848 Brushes categories only shown in sculpting and image paint modes

---

asset_bar_op.py

#854 Show asset not available for small thumbs correctly

---

categories.py
upload.py

#861 Add Other category into subcategories and sub-subcategories

---

__init__.py
asset_bar_op.py
search.py
ui_panels.py

Folding of header menu (arrow icon like in panels)
Esc while drag dropping into scene cancels drag drop, but not the asset bar. 
Searching by License type

3 features we promised at conference

---

global_vars.py

#873 Add tip about ESC to cancel drag-and-drop

---

__init__.py
asset_bar_op.py
ui_panels.py

#878 Limit asset_popup_counter to 5 which is limit for hint to be shown

---

asset_inspector.py

fixes #884 
1. Removes ugly warning message from importing the 3D add-on when is not enabled.
2. Moves the import into function checking if object is printable.
3. Fixes the wrong class names imported from the 3d object add-on.
Function check_printable is still commented out as was before, but is completely ready to be uncommented and be delivered to users.

#884 Fix check_printable, prevent ugly warning message

---

daemon/daemon.py
daemon/daemon_search.py

#903 Fix that some thumbnails are not downloaded

---

bl_ui_widgets/bl_ui_widget.py

fixes #688 
Double try: inside each other prevented the check fo image validity to work well

#688 Fix annoying tooltip image disappearance

---

download.py

#913 Remove download from view if it fails on append

---

autothumb_material_bg.py
bg_utils.py
daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_utils.py
daemon_lib.py
download.py
paths.py

wouldn't before work if asset wasn't downlaoded, now should work needed preferences, and completely new function that wasn't implemented in daemon - blocking download. needs testing if everything else works it seems.

Attempt to fix the regenaration of thumbnail with downloading

---

bkit_oauth.py
search.py
utils.py

#918 Pasting API key does not trigger profile fetch

---

global_vars.py

#947 Add tip about mouse wheel rotation when drag and dropping

---

upload.py

#951 Error in upload check for file existence of relative thumbnail path

---

daemon_lib.py

#966 Fix name of the function for location of dependencies in the error report in daemon_lib

---

asset_inspector.py
utils.py

fixes #970
tested with 4.0.3, 3.0.1, 3.2.2

#970 Update context in delete_hierarchy to fix replace active models in Blender 4

---

asset_drag_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py
download.py

because it used wrong exception handler.
also fix a try in exception handling in try_finished_append
fix downloader for hdris and similar, where there's no downloader in scene.

Fix check_image_exists

---

search.py
ui_panels.py

fixes #974
plus a small cleanup of unused code

#974 Add search_texture_resolution to HDRs

---

upload.py

#997 Do not check thumbnail abs path for HDRs

---

upload.py

The check for thumbnail would disable file upload if you only want to reupload main file

The check for thumbnail would disable file upload if you only want to reupload main file

---

upload.py

fixes #1008 
was checking for thumbnail in a wrong way

Fix brush upload

---

.github/workflows/PR.yml
.github/workflows/main-push.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

 #1048 Make the isort check optional 

---

daemon_lib.py

#1051 Fix get_client_version() which was failing due to .DS_Store

---

client/login.go
client/main.go

#1046 Incomplete headers in request after subscription of new add-on

---

client/main.go
client/structs.go

#1054 Fixes metadata reupload, adds basic error reporting on this request

---

LICENSE
asset_bar_op.py
autothumb.py
bg_utils.py
client/download.go
client/login.go
client/main.go
client/networking.go
client/structs.go
client/utils.go
client/utils_test.go
client/wrappers.go
daemon_lib.py
daemon_tasks.py
dev.py
disclaimer_op.py
global_vars.py
image_utils.py
log.py
overrides.py
persistent_preferences.py
tasks_queue.py
test.py
test_daemon_lib.py
test_init.py
test_paths.py
timer.py
ui_panels.py

#1062 Add license file and license mentions to all files

---

client/main.go
client/structs.go
ratings_utils.py

#1071 Client needs to send DELETE request on rating deletion

---

client/download.go
client/main.go
client/main_test.go
client/structs.go
upload.py

#1067 Parse and log error responses from failed HTTP requests

---

__init__.py
test.py
test_upload.py
upload.py

#1081 Add check for format and maximum number of tags

---

client/download.go
client/main.go

#1084 Report Download progress before reading resp.body for better fedback on intercepting proxies

---

search.py

#829 Do not prevent repetetive searches

---

asset_bar_op.py
search.py

#1090 Fix empty search result breaking all following searches

---

.gitignore
dev.py

#1091 Add script for release with signed binaries

---

dev.py
test_upload.py
upload.py

#1100 Fix tag validation which fails on empty tag field before private upload 

---

client/main.go
client/utils.go
upload.py

#1102 Fix reupload: set asset's ID and BaseID in Blender only when needed, fix metadata response for update of asset

---

client/main.go
client/main_test.go

fixes #1113 
- do not use scientific notation for huge numbers in DictToParams
- add tests for DictToParams

#1113 Fix upload for complex assets

---

client/main.go

#1111 Fallback client start to 127.0.0.1 if localhost fails

---

autothumb_material_bg.py
autothumb_model_bg.py
bg_utils.py
client/main.go
client/wrappers.go
daemon_lib.py
test_upload.py

fixes #1099
- moves whole upload into one step
- there is still room for improvement: created issue #1127 for this

#1099 Implement blocking file upload in one step

---

asset_drag_op.py

#1141 Fix drag drop in viewport when over plane and facing up, or also under plane and facing down.

---

client/structs.go

fixes #1132 
was caused because leather category has videos generated.
```
"files": [
{
"fileType": "blend",
"downloadUrl": "https://www.blenderkit.com/api/v1/downloads/83163/",
"uuid": null,
"fileThumbnail": null,
"fileThumbnailLarge": null,
"created": "2021-10-06T03:35:02.012403+02:00",
"modified": "2021-10-06T03:35:05.978375+02:00",
"mimeType": null,
"resolution": null
},
{
"fileType": "resolution_0_5K",
"downloadUrl": "https://www.blenderkit.com/api/v1/downloads/312821/",
"uuid": null,
"fileThumbnail": null,
"fileThumbnailLarge": null,
"created": "2024-01-30T09:26:47.593399+01:00",
"modified": "2024-01-30T09:26:47.593410+01:00",
"mimeType": null,
"resolution": null
},
{
"fileType": "resolution_1K",
"downloadUrl": "https://www.blenderkit.com/api/v1/downloads/312820/",
"uuid": null, …
```

#1132 structs.go: AssetFile.results.files.resolution should be of type int

---

__init__.py
test.py
test_utils.py
ui_panels.py
utils.py

#1150 Fix information about private storage remaning and quota

---

client/wrappers.go

#1122 Show detailed error message if nonblocking request ends with non 200 status

---

bg_utils.py
client/download.go
dev.py
icons.py
paths.py
ui_panels.py
utils.py

fixes #1160 
enables to open asset folder from right click menu, only visible when at least one resolution is downloaded/folder exists.

 #1160 Add button to open directory containing the asset

---

autothumb.py

not sure when this got into the code...

Fix paths for newly generated thumbnails

---

daemon_lib.py
daemon_tasks.py

#1174 Remove mutable data types as default values for function parametres

---

client/download.go
client/login.go
client/main.go
client/utils.go
client/wrappers.go

#1173 Improve error logging on requests in Client

---

search.py

fixes #1162
- handles the link manipulation directly in check_clipboard()
- in clean_filters() set true_hdr via "key" to prevent update function leading to unnecessary search
- save unnecessary search because we do not need to unset search_keywords in clean_filters - the asset_type is already switched in check_clipboard()
- keep history in original asset_type, because we do not place the link there, then clean it, then switch, then search
How to test:
- search model for dog
- copy link on website to HDR, should search it, should be fine
- copy another link to HDR, should search, no errors
- copy link to material, should search it
- check if models have original dog search, HDR has the second linked asset, material has the linked asset

#1162 Fix recursive calls on HDR asset-links

---

__init__.py
ui_panels.py

fixes #1172
Needs some checks from you @vilemduha

#1172 Add EEVEE_NEXT engine which is introduced in Blender 4.2

---

search.py

#1184 Enable check_clipboard() on Linux

---

asset_drag_op.py

#1128 ui_panels not imported in asset_drag_op.py

---

search.py
utils.py

#1269 Enforce (pre)release update checks for validators/staff accounts

---

__init__.py
append_link.py
asset_bar_op.py
asset_drag_op.py
bg_blender.py
categories.py
client/structs.go
download.py
paths.py
search.py
ui.py
ui_panels.py
upload.py
upload_bg.py
utils.py

This adds node group asset types. We need to finish category system, but all seems to work well now. 
On todo might be drag drop into node editor, by now it auto appends to the current node tree. 
Also, the asset type is now under experimental features, so we can upload some nodes first.

Nodegroup asset type

---

__init__.py
daemon_lib.py
search.py
ui_panels.py

#972 Add search filter blender_version_min/max

---

client/main.go

fixes #1285 
How to test:
1. start download of some big asset
2. close blender during download
3. previously just before shutdown Client would panic and crash, now it prints warning and says Goodbye! as it should
No big deal as it happened only before last moments of shutdown. But it is nicer to cover it. Also it prevents situations if something like that anytime happened during normal run in the future. Will print warning so the devs will know something is how it should not be really.

 #1285 Handle nil pointer to task during shutdown gracefully

---

ui_panels.py

tweak drawing of props in asset popup card to to enable more nicely clickable props Add a few TwinBru specific parameters.
ProductLink for assets that have it. ProductLink is something that can be used for more than TwinBru... much more! goes along with:
- adding new parameters as on devel
- changes in server server asset tools

TwinBru lib syncing:

---

client/main.go

#1302 Improve UI messages for un/bookmarking

---

upload.py

- capitalize the title for better looks
- add some question, so user knows what they accept/reject

Fix #1323 Improve text for private asset upload popup

---

asset_inspector.py

- ob.to_mesh() can return None sometimes, so we need to check this before accessing mesh.polygons etc
- reformatted the nesting

Fix #1318 Func check_meshprops() fails on some assets and blocks upload

---

client/download_test.go
client/main.go
client/main_test.go

- remove unused SubscribeAvailableSoftware

Add some more unit tests of main.go and download.go

---

download.py

- before calling bpy.context.active_object.active_material.library check for existence of active_object and active_material
- reformat extreme nesting

Fix #1300 Second application of same material fails

---

asset_drag_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py
download.py
search.py

- the thumbnail gets removed after first download, could not figure out why
- as fix adding additional image load when thumb is not present, fallback solution

Fix #1153 Second drag of assets does not show image and throws error: Image is invalid- draw function

---

search.py

Fix #1358 Zero files in asset in search results leads to error when user is validator and it fetches comments

---

client/main.go

- catch windows.WSAEADDRINUSE (aka 10048) explicitly
- catch windows.WSAEACCES (aka 10013) explicitly

Fix #1369 EADDRINUSE not catched on Windows

---

search.py
upload.py

fixes #1366
- change model_style to modelStyle
- change material_style to materialStyle

Fix #1366 Deprecate snake_case in asset parameters, use camelCase instead

---

client/main.go
client/structs.go
client_lib.py
utils.py

#1387 Add identificator of individual windows of Blender

---

ui_panels.py

Fix #1409 Liking of comments on asset detail stopped working

---

bkit_oauth.py
datas.py

Fix #1421 logout should not delete BKIT_PROFILE, instead it should reset it to empty state by calling datas.MineProfile()

---

upload.py

Add #1432 Add option to set sexualized content flag in validators' fast metadata edit

---

client/login.go
client/main.go
client/main_test.go

Fix #1353 Mux locks missing in some calls to global maps in Client

---

comments_utils.py
ui_panels.py

This shows comments in the add-on immediately after posting. Basically fills in the local comments data

Fix #260 -show comments immediately

---

search.py

…o switch to that asset type.
so you can type something like 'car model' or 'wood material', 'outdoor hdri' or similar and it should work well.

Auto-switch asset type if user types asset type in search field

---

blender_manifest.toml

Fix #1458 Permissions must be a table of strings in blender_manifest.toml

---

__init__.py

fixes #1460
- also add annotation of Printables into the experimental_features description

Fix #1460 Remove Nodegroup from experimental

---

bkit_oauth.py
client_lib.py
colors.py
disclaimer_op.py
download.py
paths.py
ratings_utils.py
reports.py
search.py
timer.py
utils.py

Fix #1463 Errors should stay longer in the GUI

---

client/download.go

fixes #1480 
fixes #1484 - by removing the need to raise the error
- do not raise error on missing Content-Length, respectively resp.ContentLength == -1
- instead set progress of the downloa to 66% to signal to user it is not good track (better than 1% or 99%)
- report how much is downloaded in the task message

Fix #1480 Some assets might miss Content-Length header

---

asset_bar_op.py
search.py

Fix #1487 Trigger default search when AssetBar is opened and there are no search results present

---

asset_bar_op.py

- Set verification status to "all" for validators when searching by author. This speeds up validation work.

Validators search improvement

---

override_extension_draw.py

Fix #1507 Remove spammy print from the override_extension_draw.py

---

paths.py
ui.py

Fix #1500 Asset detail popup is broken for printable asset type

---

ui_panels.py

Fix #1512 Spammy error on material search

---

__init__.py
blender_manifest.toml

DO NOT MERGE
just prepared for tomorrow release

Bump up version to 3.15.0.250321

---

bkit_oauth.py
override_extension_draw.py

When logging in or out, the update was needed.
Also try to periodically update for 5 minutes if user goes to buy the addon with the button.

Properly update cache of extensions

---

upload.py

fixes #1534
- remove duplicate checks placed in wrong function

Fix #1534 Description and tags should not be required for private upload

---

__init__.py
datas.py
ui_panels.py
utils.py

Fix #1427 Make auto-map settings permanent

---

upload.py

Fix #1544 Asset license error when using own assets

---

download.py

Fix #1576 download.duplicate_asset() has to return 2 values every time

---

datas.py
upload.py

Fix #1545 Addon fails when PrivateQuota is null in JSON -> later None

---

upload.py
utils.py

Fix #1571 Show the names of the objects in report from prevalidate_model()

---

ui_bgl.py

Fix #1574 Drag and drop outlines (box and pointy line) does not work in Blender 4.5

---

client/download.go
client/main.go
client/structs.go

fixes #1486 
WIP - logs needs to be removed and compression needs to be verified to work actually.

Feature #1486 Enable compression on downloads again

---

test_client_lib.py

fixes #1587 
- do not use empty space " ", use + as the addon does

Fix #1587 Make Test05SearchAndDownloadAsset to use + in the asset names

---

CONTRIBUTING.md
download.py
utils.py

fixes #1442 
- before the add-on gives up prematurely, it can try switching to the "OBJECT" mode - because why not trying it? why giving up?
- the same applies for brushes

Fix #1442 Model/material append fails prematurely if not in "OBJECT" mode

---

append_link.py
download.py
overrides.py
utils.py

Fix #1583 Log extensively every use of bpy.ops.object.select_all() to catch more info about can't modify blend data in this state (drawing/rendering)

---

append_link.py
asset_drag_op.py
download.py
ui_panels.py

 Fix #1594 Do not use mutables as default arguments 

---

append_link.py
asset_drag_op.py
download.py
upload_bg.py

quite complex behaviour:
- can switch node editor type
- can add modifier/node tree
- adds on mouse position.

Handle drag dropping node groups into node editors

---

ui_panels.py

fixes #1550 
- also add search field for the printables

Fix #1550 Search box in the right panel is only in sculpt/paint mode

---

download.py

fixes #1601 
- Remove filesSize from asset data in udpate_asset_data_in_dicts() - it is not needed and was causing an overflow of int32 in Windows
- Keep filesSize in search results for display purposes
- Maintain core asset functionality (URLs, file paths, metadata) in the scene['assets used']

Fix #1601 Remove overflowing filesSize from scene['assets used'] in udpate_asset_data_in_dicts()

---

dev.py

- Praha was used last year, we have changed to english variant

verify_client_binaries() should expect BlenderKit certificate with city of Prague, not Praha
