__init__.py

Fixes #3
Fixes #5 
Tested on blender-3.0.0-beta+v30.3844e9dbe771-linux.x86_64-release. Needs a test on Windows and if works properly if used outside the Blender.

Issue #3 - Fix import path of sentry_sdk

---

dependencies.py
timer.py

aiohttp install might get screwed by autoupdater.
This prevents blender from getting stuck when trying to start daemon perpetually, by enabling async loop in timer.
by trying import from aiohttp sublibrary we can find out that aiohttp is actually installed wrongly.

Circumvent autoupdater possible issues

---

__init__.py
addon_updater.py

Fixes #97
Fixes #108 
This PR changes the behaviour of addon-updater backup creation. It does not copy the addon into backup location but instead it moves it there. And then copies it back.
Due to that all opened .pyd files are moved into backup location and original location is free of files used by another processes.

Do addon backup in update by move and copy back

---

__init__.py

@vilemduha Bumping the version to 3.1.4. And also I realized, we can add warning to the bl_info, which gets parsed even though the auto-update fails and imports and everything is corrupted... Blender parses bl_info as string, so it will be shown. Please take a look on it in Blender GUI if it looks good and if wording is correct. I think this could provide needed information to the users.

Bumb up version and add warning info about update

---

bl_ui_widgets/bl_ui_image.py

fixes #159 
Please @vilemduha take a look. __image.name seems to be unused in the `bl_ui_widgets/bl_ui_image.py`. It is not set or get or mentioned anywhere in the file. Does it have any hidden function?
Removing it fixes the error printing to console and also search seems to work as expected.

Do not set unused self.__image.name in set_image()

---

paths.py

Hello BlenderKit Devs,
First of all, thank you for BlenderKit!  Most free desktop OS follows
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which defines where files should be
looked for by defining one or more base directories relative to which files should be located.
BlenderKit defines a `Global Files Directory` in `$HOME/blenderkit_data`,
which according to aforementioned specification, should be in
`$XDG_DATA_HOME/blenderkit_data`.  Additionaly, `$XDG_DATA_HOME`
is a single base directory relative to which user-specific data files should be written.
Thank you.

Add support for XDG Base directory

---

__init__.py
asset_bar_op.py
download.py
ratings.py
ratings_utils.py
search.py
tasks_queue.py
ui.py
ui_panels.py

- remove obsolete bkit_ratings, so these aren't stored on datablocks anymore and aren't saved in the .blend file
- remove some unused bgl and panel drawing code too
- Fast rating (R) operator was fixed and also shows a thumbnail now
- Work on the separate ratings panel, is commented out still - needs to store ratings in some list of custom props and have better UI
- Experimental Star Button implemented as a gizmo directly in the 3d view, accessible only to validators right now

Cleanup rating code:

---

bkit_oauth.py
global_vars.py
search.py

fixes #219 
Instead of using lists, I have used collections.deque, which is optimized to be used as queue. Appends and pops does not move data in memory!
- I have specified history queue to be a fixed size of 20 things, we does not need to check it anywhere
- it prepends from right, from last element, as lists normally do
- it can be accessed as a list deque[-1]

Fix broken search after 20 search requests

---

__init__.py

Increasing version to 3.1.6 and shortening warning message, so it is fully readable in preferences menu. It is kind of strange message due to restricted number of characters.
@vilemduha please confirm it is ok. We can then relase.
The zip is uploaded in Slack so team can test. If nothing is found, we can release tomorrow.

Bump up to version 3.1.6

---

bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py

fixes #217 
The thumbnails need a dot (.thumbnailname.jpg) on the beginning of their name so they are invisible to casual user (unless he types a dot)
This behaviour was always default but got lost for one variant of loading images - we should deduplicate the code in the bl_ui_widgets library

Fix issue #217

---

.github/workflows/close-inactive-issues.yml

fixes #228 
- issues marked as `unstale` or `NEED ANSWER` will not stale/close,
- issues which have milestone - are planned for release of specific version will not stale/close,
- issues which have an assignee will not stale/close

Improving automatic closing of issues

---

utils.py

since blender 3.2 there was an undocumented api change -
cube mapping got inverted and fixed.

Fix automap

---

__init__.py
timer.py
utils.py

- adds token_token into preferences
- passes the token in headers as `uuid-token`
- it is checked (and created if needed in the startup_timer)
- the UUID is generated via uuid.getnode() which should generate the same UUID for the same system, tried with several Blender versions and it works! https://docs.python.org/3/library/uuid.html#uuid.getnode
- passes the `addon-version` in headers in format `X.Y.Z.YYMMDD`

Add UUID token

---

addon_updater_ops.py
bkit_oauth.py
categories.py
comments_utils.py
daemon/daemon.py
daemon/oauth.py
daemon_lib.py
download.py
global_vars.py
paths.py
ratings_utils.py
resolutions.py
search.py
ui.py
ui_panels.py
upload.py
upload_bg.py

fixes #301
- enables PKCE in the add-on
- moves and unifies switching between local/devel/stagging/production into global_vars.SERVER instead of using debug value
**How to test:**
- run, try login and search
- set `global_vars.DEBUG=BLENDERKIT_DEVEL` and try to login and search
**Testing of older add-ons on devel:**
- BlenderKit 2.93.0 on Blender 2.93.10 on devel - login, search and download is OK
- BlenderKit 3.0.4 on Blender 3.0.0 on devel - login, search and download is OK
- BlenderKit 3.1.0 on Blender 3.0.0 on devel - login, search and download is OK
- BlenderKit 3.1.5 on Blender 3.0.0 on devel - login, search and download is OK
- BlenderKit 3.2.0.220920 on Blender 3.0.0 on devel - login, search and download is OK 
(one must set debug_value and also set globals.SERVER to devel, no …

Issue #301 - Add support for PCKE OAuth

---

__init__.py
daemon/daemon.py
daemon/globals.py
daemon_lib.py
timer.py
utils.py

fixes #204
Aiohttp by default uses IPv4 and IPv6 for its connectors. When trying with DNS resolvers, I have faced errors with SSL which are quite the same as some users report and we thought it is about their proxy/firewall. It was fixed for me by defaulting aiohttp to only use IPv4. So I am trying to default to IPv4 in this PR and will send the build to the users with SSL problems, to see, how it works.

Add option to choose IP version

---

bl_ui_widgets/bl_ui_draw_op.py

This is actually putting back a fix that was already there, for some testing it was tweaked and accidentaly commited such

fix the 'missing operator' messages.

---

ui.py

disabled assetbar starter redo and register, this doesn't show the redo panel and prevents the reported crash.

fix #240 - assetbar redo

---

daemon/search.py
search.py
test_daemon_lib.py

fixes #369
- uses .webp thumbnails if Blender version >= 3.4.0
- uses .webp images if webpGeneratedTimestamp is not None (None means webp is not yet generated), in that case it fallbacks to use non-webp urls

Webp thumbnails

---

search.py
ui_panels.py

Send first search after installation of addon directly to daemon instead of to UI keywords field, avoids occasional errors from people typing into that string.
also make search field slightly wider.

Fix first search string

---

daemon/daemon.py
daemon_lib.py

fixes #380 
So the daemon exited with return code 0 even when some error happened. This code makes the daemon to exit with correct return codes which are then handled by add-on which shows useful information how to fix the issue, or how to report it into bug tracker.
Also this PR adds some error codes which we got previously reported on the GitHub.

Handle daemon startup errors correctly

---

.github/make-tests-matrix.py
daemon_lib.py
timer.py

Fixes #414 
This fixes a strange error: for some reason on my Windows machine the requests for daemon report stopped to fail when daemon is not running. Instead of error and trying later, the request.get gets stuck for ever, which means the daemon is never started and Blender is completely frozen, waiting for the request for ever ever ever...
This did not happen on the Windows before, must be some update or something which causes the Windows OS instead of replying "port closed" to not reply at all... This patch fixes all the requests to daemon to have a timeout, after which they fail.

Define timeout in requests from add-on into daemon

---

asset_pack_bg.py
autothumb_material_bg.py
autothumb_model_bg.py
bkit_oauth.py
categories.py
comments_utils.py
daemon/assets.py
daemon/comments.py
daemon/daemon.py
daemon/disclaimer.py
daemon/profiles.py
daemon/search.py
daemon/tasks.py
daemon/utils.py
daemon_lib.py
disclaimer_op.py
download.py
global_vars.py
paths.py
ratings_utils.py
rerequests.py
resolutions.py
search.py
test_daemon_lib.py
timer.py
ui_panels.py
upload.py
utils.py
version_checker.py

Delayed into 3.5.0. Merge after 3.4.0 is release.
fixes #357 
Fixes:
- adds subscribe_new_addon func into daemon - this func runs when new addon appears and creates all the internet tasks needed after the startup like: fetch disclaimer, fetch categories etc. 
- improves fetch disclaimer - now is initiated from daemon
- fetches categories from daemon
- daemon fetches notifications when new Blender instance appears (and user is logged in)
- fetches comments - create, rate, mark as private, get
- removes unused file asset_pack_bg.py
- removes unsused functions from resolutions.py
- moves notifications requests into daemon
- update comments after comment creation/like/public
- moved get_download_url into daemon
- moved gravatar fetch into daemon
- moved fetching data about logged-in user into …

Exodus of network requests from add-on into daemon

---

search.py
ui_panels.py

to avoid  "Python int too large to convert to C int" when writing asset data to scene used assets data.

fix #426 convert filesSize to kb

---

__init__.py
dependencies.py
dev.py
global_vars.py

fixes #187 
premise: We do not want to bundle for more than one version of Python, right? Once Blender with python 3.11 is released we gonna bundle 3.11 dependencies and if somebody is using older Blenders with python 3.10, the installation will fallback to pip install from requirements.txt file, is this thinking correct? Do we agree, @vilemduha?
Bundling for more than one version would increas the size of the add-on, which I believe is not great.
How this PR works:
1. add-on checks if dependencies are bundled for the same python version as Blender is running on - if so, the addon will copy them into `daemon/dependencies/3.5.0/3.10/preinstalled`, if they are not the same, no copying is performed
2. as before the add-on adds preinstalled and installed dirs into PATH
3. tries to import …

Support dependencies for different versions of Python

---

asset_bar_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py
bl_ui_widgets/bl_ui_widget.py
ui_bgl.py

fixes #488, #484
there was only needed to set correctly the alpha blend instead of glblend and fix image draw function
NEEDS a lot of testing, we might have to drop support for 2.93.
-images might unload from memory, or the whole thing might be much slower now, so we really need to test well, also performance before-after

fix #488 - remove bgl module

---

ui.py

fixes #502 
When preferences.directory_behaviour is set to LOCAL user truly wants her assets in the project. To do that add-on needs defined path - and for that project must be saved. This commit blocks download without saved project in local mode.

#502 Require saved project for download in local dir mode

---

__init__.py
daemon/daemon.py
daemon/utils.py
log.py

fixes #517 #508 
reconfiguring sys.stdout to explicitly use utf-8 encoding, UTF-8 default encoding
set streamHandller.stream to stdout so special chars are printed fine

#517 Fix decoding error when OS use gbk encoding

---

ui_panels.py

This could lead to a better offline experience. All the error messages can be annoying if you just use Blender and are offline for whatever normal reason, like being on your travels ;)

Don't show search, upload panels and header bar when offline

---

download.py
upload.py
utils.py
version_checker.py

fixes #494
And there is follow-up issue for all categories, which can have the same problem as description and tags had #554 - but hm, why it is correct in the fast metadata?

#494 Update description and tags on download from search result data

---

daemon/tasks.py

So this was reaaaaaly hard to debug - the results in daemon could get overwritten (file paths before all), because the task object had a dict for the results that wasn't copied on init, so it was shared between task objects.

Fix failing appends after download

---

asset_bar_op.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_draw_op.py
bl_ui_widgets/bl_ui_image.py
bl_ui_widgets/bl_ui_label.py
bl_ui_widgets/bl_ui_widget.py
disclaimer_op.py
download.py
search.py

Reduce asset bar draw calls.
Until now, the library bl_ui_widgets did draw every modal event(!)
Now only when something real happens should redraw.
This is done directly in the widgets library, so operators don't have to care when to call tag_redraw:
- all relevant setter functions for properties have a check for change and tag redraw
- several other substantial functions that update the look of the assetbar call tag redraw (mouse in/out, position update)
During animation, asset bar also gets hidden.
All this causes huge CPU savings on my macbook air

Asset bar performance

---

asset_bar_op.py
daemon/search.py

The main problem was if server returns another response than 200, the response content still got written into a file.
handle better check for existing files to avoid pink or empty thumbnails, and provide thumbnail_notready.jpg instead.
This still doesn't show fallback thumbnails if server returns bad webp. I concluded implementing the fallback is too complex for now considering that it actually fixes an error from our server.

webp - don't write error to .webp file

---

daemon/ratings.py
ratings_utils.py

fixes #586 
- adds rating and work hours locks
- locks prevents property.update() function to send ratings as if user clicked
- limit ratings on daemon side, rating task sleeps and waits for updates
- if no updates are sent, daemon finishes the task by sending them to server

#586 Limit ratings requests and send only when needed

---

__init__.py
disclaimer_op.py

fixes #570 
Adds option to disable online announcements aka disclaimers into the preferences:
```
announcements_on_start: BoolProperty(
name="Receive online announcements when starting Blender",
description="Show crucial online announcements from the BlenderKit service. These are official messages from the BlenderKit team regarding maintenance, events, and other relevant information.",
default=True,
update=utils.save_prefs
)
```

#570 Allow users to disable online annoucements

---

append_link.py
asset_bar_op.py
categories.py
dependencies.py
paths.py

fixes #556 
This is mostly cosmetic change which will however improve the way user is informed about dependencies import failure. For now it was mostly silent, so giving it some visibility should help the users to know that something is wrong and that they should seek for help.
- #93 installation can fail due to missing libcrypt.so.1, this should be shown to GUI
- other dependency imports should be also shown to GUI
- check and report imports for aiohttp and certifi separately

#556 Improve feedback on deps installation failure

---

daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_comments.py
daemon/daemon_disclaimer.py
daemon/daemon_oauth.py
daemon/daemon_profiles.py
daemon/daemon_ratings.py
daemon/daemon_search.py
daemon/daemon_tasks.py
daemon/daemon_uploads.py
daemon/daemon_utils.py
upload.py

Hopefully this PR finally find the right way how to handle errors for requests:
1. it makes a request
2. saves resp_status and resp_text
3. if needed resp.json() is called by the function
4. !! runs resp.raise_for_status() which will raise Exception if status code was >= 400
5. in except we call function which extracts meaningful error message from: resp_text, resp_status and Exception, it works like:
- tries to convert resp_text into JSON,
- if JSON is doable, it tries to get "details" and from details get all keys and values (this is how server reports errors)
- if JSON is present, but details are not, this is probably error from S3 or other service and JSON as string is just used
- if JSON is not present, it combines information from Exception and from resp_text

#399 check errors reported in JSON from server

---

upload_bg.py

This is a blender issue where blender sometimes wants to pack textures that aren't actually needed and are somehow still in the project. This prevented upload completely, where the task of the creator is to check correct upload anyway. Not sure how to pass a warning to the user, since it's all in a bg process that is run from daemon.

Fix upload in case not all textures are packed correctly.

---

__init__.py
daemon_lib.py
timer.py
ui_panels.py

fixes #702 
- groups preferences into three groups: locations settings, gui settings and networking settings, beside that there are login stuff in the begining and autoupdater in the end.
- adds greyed list of important paths in the end of preferences - users will know which directories to delete to clean the add-on, or for whatever other reasons, I think this could be quite useful.
- adds option to set search field width - default 0 keeps the width automatic, anything higher sets it to fixed value.
- removes some unused properties

#702 Add property for search field width, clean preferences menu

---

bkit_oauth.py
daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_globals.py
daemon/daemon_oauth.py
daemon_lib.py
search.py
timer.py

fixes #733 
- refresh preventively 3 days before token expiration
- if any request fails due to wrong API key and refresh does not exist, unlog
- if refresh key exist, try to refresh and get fresh new tokens
- if refresh fails, unlog the user
- do not request refresh from server with same refresh token 2 times

#733 Improve handling of timed out API key token

---

__init__.py
autothumb.py
autothumb_material_bg.py
autothumb_model_bg.py
daemon/daemon_assets.py
daemon/daemon_uploads.py
download.py
log.py
tasks_queue.py
test.py
test_init.py
timer.py
ui.py
utils.py

fixes #746 
- starts background Blender instances with `--factory-startup` flag, which disables all non-default add-ons and ignores user preferences - this makes the Blender in background independent of individual user's configurations, addons, makes stable platform form our renderings of thumbnails, unpacking etc...
- uses flag `--addons blenderkit` to enable BlenderKit in the background Blender
- for some reason BlenderKit is not in list of enabled addons, meaning we cannot access preferences - so there are few changes so all code executed in the background (aka with --factory-startup) does not call preferences, uses bpy.app.factory_startup to detect situations when we need to turn off using preferences, using bpy.app.background was crashing the tests (as tests needed to use preferences …

#746 Use background Blenders with --factory-startup

---

daemon/daemon_profiles.py
paths.py

fixes #749 
- rename bkit_temp to bktemp_<username>
- adds username to BlenderKit temp directory, so two user can't share the same directory
- use only alpha numeric characters from the username
- fixes problem for UNIX, where default tempdir was /tmp for every user, now /tmp/bktemp_<username>

#749 Use different tempdir for every user

---

utils.py

fixes #755 
- if major version of running Blender is higher than asset's, return False and do not check more
- if minor version is higher, return False and not check more

#755 Fix broken check for newer asset version

---

daemon/daemon.py
daemon/daemon_assets.py
daemon/daemon_comments.py
daemon/daemon_oauth.py
daemon/daemon_profiles.py
daemon/daemon_ratings.py
daemon/daemon_search.py
daemon/daemon_tasks.py
daemon/daemon_utils.py

fixes #667 
not really fixing the #667 as the download sometimes continues after network is reconnected, but sometimes it does not continue and fails after a while. We would need really sofisticated code to handle this, which we might add in the future. During the investigation I've found some ways to improve, which I add in this PR.
- catching the asyncio.CancelledError in handle_async_errors
- set_name for all asyncio tasks, so they are tied with the daemon.Task
- in comments async tasks was not save into daemon.task.async_task, setting it now so they can error the task on failure

#667 Catch asyncio task giving CancelledError when calling task.exception()

---

__init__.py
asset_bar_op.py
ui_panels.py
utils.py

fixes #754 
- enables Bookmarks
- remove bookmarks from text of experimental_features property
- add info, that there are no experimental features available in this version into experimental_features
- moves asset bar's show_on_start to GUI part of settings

#754 Enable Bookmarks outside experimental features

---

upload.py

fixes #764 
- do not check non existing brush's props.thumbnail
- instead check utils.get_active_brush().icon_filepath
- write custom more informative error message for missing icon of brush

#764 Fix broken check for Brush's thumbnail

---

__init__.py
asset_bar_op.py
bl_ui_widgets/bl_ui_draw_op.py
disclaimer_op.py

fixes #770 DO NOT MERGE, WE NEED TO DISCUSS THIS
- fixes StructRNA of type BlenderKitDisclaimerOperator/BlenderKitDisclaimerOperator has been removed on unregistration
- fixes unfreed memory on Blender quit with BlenderKit enabled

#770 Fix StructRNA being removed and unfreed memory

---

autothumb.py
autothumb_material_bg.py
autothumb_model_bg.py
daemon/daemon_assets.py
daemon/daemon_uploads.py

fixes #777
- gets compute_device_type when starting background thumbnail render
- passes it via JSON to background Blender
- sets Cycles compute_device_type in the background Blender

#777 Pass Cycles compute_device_type via JSON to background Blender

---

autothumb_material_bg.py

this fix is only from blender 3.3 (since it uses the new apply transform operator option to separate instances), but I'd say let's survive that in blender 3.2 there can't be fluid preview rendered.

Fix fluid thumbnailer

---

utils.py

because the selection (select material slot) couldn't work - there wasn't a material slot yet (material gets applied after creating UV map)

First time automap wasn't applied

---

__init__.py
search.py
ui_panels.py

fixes #760 
- use quality for all asets
- also join it for all assets, so it's linked - quality limit filter is now shared between asset types

Use quality limit for all assets

---

bkit_oauth.py
daemon/daemon.py
daemon/daemon_configurator.py
daemon/daemon_oauth.py

fixes #805 
- logs location from which daemon loads certificates (certifi, blenderkit cert chain, custo CA certs)
- in /debug it prints detected and used certificates

#805 Improve logging around SSL certificates

---

__init__.py

fixes #803
- updates text
- allows to specify CA certs without selecting Custom proxy settings
- changes proxy_ca_certs to subtype from DIR_PATH to FILE_PATH

#803 Update UI and text around CA certificates

---

__init__.py
addon_updater_ops.py
asset_bar_op.py
autothumb.py
bg_utils.py
bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_image.py
bl_ui_widgets/bl_ui_widget.py
paths.py
ui.py
ui_bgl.py
ui_panels.py

restructure several functions to update sizes in assetbar (split them) update the size on each enter button, so we're sure the tooltip has correct size. Works nicely now!

Update tooltip size correctly when scaling window

---

disclaimer_op.py

fixes #958 
Error: Python: Traceback (most recent call last):
File "/Users/ag/Library/Application Support/Blender/4.0/scripts/addons/blenderkit/disclaimer_op.py", line 160, in modal
if self.handle_widget_events(event):
File "/Users/ag/Library/Application Support/Blender/4.0/scripts/addons/blenderkit/bl_ui_widgets/bl_ui_draw_op.py", line 67, in handle_widget_events
if widget.handle_event(event):
File "/Users/ag/Library/Application Support/Blender/4.0/scripts/addons/blenderkit/bl_ui_widgets/bl_ui_widget.py", line 132, in handle_event
bpy.context.region.tag_redraw()
AttributeError: 'NoneType' object has no attribute 'tag_redraw'
Disclaimer checkoval, jestli neni region None, volal self.finish(), ale funkce pokracovala dal a bylo to chycene az v dalsim behu pri `if self._finished: return …

#958 Finish disclaimer modal right away when context.area is None/False

---

ui_panels.py
utils.py

fixes #937 
- adding socialNetworks on profile where available (does not add row if they are not available)
- aboutMeUrl now does not add row if it is not available to keep proper padding (some creators now can be accepted with social portfolios)
- aboutMeUrl is now stripped of http:// https:// prefixes to save space and show the interesting part - the address, not the boring protocol.

#937 Add social links to authors' profiles

---

bkit_oauth.py
client/login.go
client/main.go
daemon_lib.py
timer.py

fixes #1018
Successful example:
```
⬡  2024/03/25 16:49:49 BlenderKit-Client v0.0.5 starting from add-on v3.12.0.240319
port=62485
server=https://www.blenderkit.com
proxy_which=SYSTEM
proxy_address=http://localhost:8899
trusted_ca_certs=
ssl_context=ENABLED
⬡  2024/03/25 16:49:49 ✅ Using system proxy settings
⬡  2024/03/25 16:49:49 🔒 SSL verification is enabled
⬡  2024/03/25 16:49:49 🤝 New add-on connected: 30826
<- 2024/03/25 16:49:50 ✅ disclaimer (11535200-65b0-4e49-989c-125bf91692c2)
<- 2024/03/25 16:49:50 ✅ categories_update (f1e637d9-7e16-4d3f-9730-13e8a13932b8)
⬡  2024/03/25 16:49:56 🆔 Add-on (30826) has created OAuth2 session (code_verifier=redacted, state=redacted).
⬡  2024/03/25 16:49:59 🆔 Token retrieval OK (grant type: authorization_code)
<- 2024/03/25 16:50:00 ✅ …
```

#1018 Revoke OAuth2 tokens during logout

---

client/main.go

fixes #1057
This is a quick fix to solve problems with already released versions of the add-on. For the robust solution which will handle incompatibilities between different versions of the BK-Client, #1044 needs to be implemented.

#1057 Reject old addons in Client, so they start daemon on their own

---

client/download.go
client/main.go
client/utils.go
client/utils_test.go
paths.py
test_paths.py

fixes #1147 
- Make sure in Client that filepath is not longer than 250
- Make sure it is not longer even at the start of download when add-on checks download dirs - if LOCAL/assets/models is longer, then there is no need to send it to Client - it will not get shorter by appneding another dir and filename, both with UUIDs
- Synces Slugify in Python with Go implementation
- Adds python tests for slugify, server_to_local_filename and extract_filename_from_url, test data are the same as in Go tests for go variants of these functions, so we can be sure they behave the same

#1147 Ensure filepath is not longer than 250 on Windows, sync Slugify in Python and Go

---

asset_bar_op.py
ui_panels.py

#1168 Prevent asset download if mouse is in categories and over asset bar at the same time

---

.github/workflows/win7-build.yml
client/go.mod

fixes #1105 
Go 1.21 and 1.22 has dropped support for Windows 7. Even though Blender 3 nor 4 has support for Windows 7, we still have few users running hacked Blender on Windows 7. To let them use BlenderKit we can build the Client with go1.20 which supports Windows 7.
This PR adds github workflow to build the Client with go1.20. It then removes all other binaries and creates blenderkit-windows7-only-{hash}.zip artifact. We can upload this artifact to issue #1105 so users on Windows 7 can install it. No other binaries are added into the .zip, as this is meant only as hack for Windows 7 users.
In future if we add on-the-go download of binaries, we could add windows 7 as downloadable binaries. But for now this is enough.

#1105 Add Github action for Windows 7 build with go1.20

---

.github/workflows/PR.yml
.github/workflows/main-push.yml
__init__.py
asset_bar_op.py
asset_drag_op.py
autothumb.py
bkit_oauth.py
blender_manifest.toml
daemon_lib.py
disclaimer_op.py
download.py
paths.py
persistent_preferences.py
ratings.py
ratings_utils.py
search.py
test_init.py
timer.py
ui.py
ui_panels.py
upload.py
upload_bg.py
utils.py
version_checker.py

fixes #1154
- fixes import to new form required by extensions, it works with previous Blender versions
- uses version in format X.Y.Z-YYMMDD in blender manifest - it would not work with .
- adds tests for correctnes of version in bl_info, VERSION const in __init__.py and version in manifest
Tested in: Blender 4.1, Blender 4.2-alpha

#1154 Make the add-on ready for extensions format

---

client/download.go
client/utils.go
client/utils_test.go
paths.py
test_paths.py

fixes #1203 
- implement in Python and Go, same functionality
- implement iidentical tests in Python and Go
- verify functionality by tests

#1203 Implement get_asset_directory_name() as rigid way how to get name of the directory

---

addon_updater.py
log.py

fixes #1233 
- set the logging using `__name__.removesuffix` instead of hardcoded "blenderkit" in the log.py file
- add emojis for the levels of log message

#1233 Set logging properly under the extension format

---

ui_panels.py

fixes #1230 
During public asset upload on Blender 4.2-Beta:

#1230 Add warning for public uploads from non-stable Blender releases

---

.github/make-tests-matrix.py
CONTRIBUTING.md
autothumb.py
autothumb_material_bg.py
autothumb_model_bg.py
client/download.go
client/main.go
client/structs.go
dev.py
test.py
test_daemon_lib.py
test_init.py
test_paths.py
test_upload.py
test_utils.py
unpack_asset_bg.py
upload_bg.py
utils.py

fixes #1231 
- due to extensions, we cannot do from blenderkit import XYZ
- package name with extensions now depends on user settings
- start BG Blender with __package__ parameter
- set the __package__ to incoming package parameter, so relative imports can be used
- use relative imports in the background scripts
- in tests detect and set the __package__ by iterating over all addons
- update docs

#1231 Fix imports in background scripts and tests

---

client/download.go
client/structs.go
download.py

Proper syncing of asset directories, between global and local asset folders.
By now, unpack stays on for even downloaded files, which is kind of stupid and is a todo to be finished.
This was serious, since assets were not synced and it caused re-download, or errors during import.
Added:
assets reusing - the issue was really connected so I joined the PRs

fix #1238 Proper syncing of asset directories

---

autothumb_material_bg.py
autothumb_model_bg.py
client/download.go
client/main.go
unpack_asset_bg.py
upload_bg.py

fixes #1263
- external repository like bl_ext.blenderkit_com or bl_ext.my_local_repo are not available during --factory-startup
- only bl_ext.user_default and bl_ext.blender_org are available in factory startup
- thus local installation works, but BG scripts installed in bl_ext.blenderkit_com.blenderkit would fail
- background scripts now enables the addon and do stuff, instead of using --addons flag (it cannot enable external repository)
- background scripts now enables the repository by parsing its name from __package__
- background scripts now enables the add-on in a way that preferences are available
HOW TO TEST:
1. Create remote repository blenderkit_com
2. Copy the add-on into: 4.2/extensions/blenderkit_com/blenderkit (normally it would be installed in …

#1263 Fix background scripts when add-on is installed in external repository

---

asset_inspector.py

fixes #1258
- its import of object_print3d_utils would fail in Blender 4.2+ as add-on 3D-Print Toolbox is no longer preinstalled
- function was unused, not-called, so no reason to have it as active code
- some user has reported that the code got into the func causing error https://github.com/BlenderKit/BlenderKit/issues/1251

#1258 Comment out unused func check_printable()

---

client/download.go
client/main.go
client/structs.go
daemon_lib.py
download.py
timer.py

fixes #1246 
Ready for review, mostly unpacking needs a check, if it works fine. From my finding the Preferences were not used inside the unpack script, so I have removed it in order to lower the complexity of the data needed.
- adds support for multiple versions of connected softwares - these are kept in `AvailableSoftwares map[int]Software // Available Softwares which are connected to the Client`
- connected softwares (aka Blender add-on, Godot plugin) does not need to actively unsubscribe on their unregistration (Godot cannot do that). Instead Client keeps track if they get silent and then unsubscribes them.
- modularizes several functions, so they do not accept huge data structs, instead they accept just needed parameters - to improve reusability
- adds endpoint …

#1246 Local communication between Client, Browser and other softwares

---

timer.py

fixes #1288 
- when global_vars.CLIENT_FAILED_REPORTS add-on does check the reports every 30 seconds to not slow Blender, this causes delay after the PORT is changed
- this change sets CLIENT_FAILED_REPORTS=0 so add-on tries hard again
- and restarts daemon_communication_timer() so the check (and start + check) happens ASAP

#1288 Change of the port does not start Client right away if the Client is not running

---

__init__.py
ui_panels.py

fixes #1292 
- all buttons have also more information about what those locations are, before it was not possible with the label
- replaces Global Dir informative text with open directory button for Global Directory (we often tell users to open and search for something there or delete it)
- replaces Temp dir informative text with open directory button for Temp Directory
- replaces Addon Dir informative text with open directory for Addon Directory
- replaces Client Log informative text with direct open of the Log File - needs to be tested on Windows, please check! <3

#1292 Make addon_dir, global_dir, client_log and temp_dir easily accessible

---

asset_bar_op.py
bl_ui_widgets/bl_ui_label.py
search.py

Shows comments for validators direclty in 3d view:
This helps validators to see the history of asset faster and make better judgement. 
By now, the formatting is just what it is... nothing fancy, but should help.

Validators comments preview

---

search.py

fixes #1305
Whole search really needs a huge refactor, it is crazy.
We should not manipulate params/queries inside function which is named query_to_url. It is completely misleading.
```python
order = []
if query.get("free_first", False):
order = [
"-is_free",
]
if query.get("category_subtree") in (
"model",
"material",
"scene",
"brush",
"hdr",
"nodegroup",
):
query["category_subtree"] = None
if query.get("query") is None and query.get("category_subtree") == None:
if query.get("verification_status") == "uploaded":
order.append("last_blend_upload")
else:
order.append("-last_blend_upload")
elif query.get("author_id") is not None and utils.profile_is_validator():
order.append("-created")
else:
if query.get("category_subtree") is not None:
order.append("-score,_score")
else: …
```

#1305 Special character breaks the search

---

__init__.py
asset_bar_op.py
global_vars.py
ratings.py
ratings_utils.py
search.py
ui_panels.py

fixes #1308
- adding B for bookmarking hoovered asset
- adding P for opening profile on BlenderKit web
- adding C for searching assets in same subcategory
- adding S for searching similar assets
- adding info to tooltips about semicolon, R, A, W

#1308 Improve documentation of shortcuts and add few new ones

---

.gitignore
client/download.go
client/main.go
client/structs.go
unpack_asset_bg.py

- bpy.path.basename(path) does not work for Windows paths with \ when running on Mac, adding backslash conversion
- resolution is sometimes not detected - fixed now

Fix #1327 Materials found on disk have missing texture, wrong texture filename parsing

---

paths.py

- env variable USERNAME can be unset on some Windows systems, it is unusual but it can happen
- python function getpass.getuser() of built-in module getpass then fallback to module `pwd`
- module `pwd` is however available only on Linux and MacOS distroc, not on Windows, which leads to import error
- catch the import error and set default username `bkuser`

Fix #1342 ModuleNotFoundError: No Module Named 'pwd' error

---

client/main.go

fixes #1391
(de facto is also fix for #1319 #1301)
- server then handles floods of clicks gracefully as multiple PUTs to database are just fine

Fix #1391 Removal of bookmark should be done via PUT value=0

---

asset_bar_op.py
asset_drag_op.py
bl_ui_widgets/bl_ui_draw_op.py
disclaimer_op.py

fixes #1375
- classes inheriting from Operator class which overrides __init__() function, need to accept *args, **kwargs
- they also need to call parent __init__ with *args, **kwargs info at: https://developer.blender.org/docs/release_notes/4.4/python_api/#blender-based-python-classes-construction

Fix #1375 Assetbar, drag and drop and disclaimer does not work in Blender 4.4.0-alpha

---

download.py
utils.py

the texture sampling bias was inverted. 
A beatiful undocumented change from Blender devs, introduced with VDM brushes. 
also fixes a stupid bug introduced in previous PR (too much AI coding!) where I didn't test properly. The map function was used with a non existing keyword.

Brushes from before 3.5 didn't work properly,

---

client/download.go
client/main.go
client/main_test.go

- handler now fetches data by AssetBaseID using the /search endpoint as requested by Petr
- it now downloads GLTF file to Godot
- file downloads to Godot are expected to have "resolution" `gltf_godot`, this is expected to be properly selected on UI or bkclientjs side
external blocks (solved):
- wait for https://github.com/BlenderKit/BlenderKit-server/pull/1169

Fix #1395 Finalize func bkclientjsGetAssetHandler() in Client

---

__init__.py
timer.py

fixes https://github.com/BlenderKit/BlenderKit/issues/1397
This is open for debate. Especially the default value for the polling.
Should we keep the default value of 500ms (avg delay +250ms)? Or should we do something like 200ms (avg delay +100ms)?

Add option to set client polling interval in add-on preferences

---

client/main.go
client/structs.go
datas.py
ratings_utils.py
search.py
timer.py

fixes #1390 
- add is_validator field to search task so Client knows whether normal user or validator does the search
- when search results come and user is validator, Client triggers batch fetch or Ratings for all assets in the result in single request
- batch Ratings are parsed and comes to add-on as normal finished ratings/get_rating tasks
- this is quite fast as the fetching goes from Client directly after search results are known, in most cases ratings are loaded before mouse goes to asset detail - I wanted to implement this architecture for a while, so it is good to see that it works
- pagination resolved in [7459b41](https://github.com/BlenderKit/BlenderKit/pull/1398/commits/7459b41f650881b68f903172d00dbd066a8e3c37)
Suggestions for future improvements:
- it could be used to fetch …

Fix #1390 Use new /ratings API endpoint for pre-fetching of ratings when user is validator

---

client_lib.py
global_vars.py
timer.py

fixes #1220
- on start add-on tries request to Client on default port
- if that fails, it starts Client on default port
- it tries to contact the Client 9 times, if it does not respond in 5.4s totally, it will print error message and start on different port
- after start on next port, it will try 10 times (cca 10.5s)
- on 21st, 31st, 41st etc. fails, it will move to starting on other ports, cycling through all available

Implement #1222 Add-on should try different port when Client start fails

---

ui_panels.py
utils.py

This ultraold bug finally got some care, seems to run at reasonable speed, since this operation only happens when opening asset popup card, or when user finishes rendering a thumbnail for upload.

Fix #809 Thumbnails with alpha channel are ugly in asset detail window

---

ui_panels.py

Before: context menu of asset in scene - go to BlenderKit submenu and see the error
Now: Submenu is correctly drawn as the Operator's author_id parameter is now filled with string, not integer

Fix #1448 function draw_asset_context_menu() fails when called with from_panel=True

---

bkit_oauth.py
client/login.go
client/main.go
client/networking.go
client_lib.py
timer.py

fixes #1044 
- add-on is now expected to send "expected_client_version" in requests to /reports
- if client finds it does not fullfil this expectation, it refuses the request (but if there is not expected_client_version = older add-ons, it will serve them - otherwise it would require users to change the ports etc... just serve it and we will hard reject once the new versions are adopted)
- add-on then handles the refusal as other HTTP errors - it assumes that this port is occupied
- add-on then also checks if BlenderKit-Client-Version headers are set in the /reports response. If they are not, it means we communicate with older Client - the add-on will raise an error = refuse to accept to communicate with this Client - assumes the port is occupied
- if port is occupied add-on moves on …

Fix #1044 BlenderKit add-on does not report it does not support running in parallel with another version of the add-on

---

dev.py

When testing, sometimes I need to deploy the addon straight to several extensions repo location for several blender versions.

enable more --install-at arguments for dev.py

---

asset_bar_op.py
global_vars.py

- Implement Ctrl+T to add new tab
- Implement Ctrl+W to close tab
- Add Ctrl+Tab and Ctrl+Shift+Tab to cycle through tabs
- Add Ctrl+1-9 to directly switch to specific tabs
- Move tab management shortcuts from handle_key_input to modal_inside
- Remove redundant logging statements

Add tab navigation keyboard shortcuts in modal function

---

asset_bar_op.py

fixes #1481
- error is kind of evil as it breaks whole search bar and one needs to restart Blender or disable/enable add-on
- in BlenderKitAssetBarOperator def enter_button check if search_index is not higher then search_results length

Fix #1481 As staff/validator switch to validated only scenes can give an error

---

ui_panels.py

- Introduce ClearSearchKeywords operator to clear the search keywords in the UI.
- Update header_search_draw to conditionally display a clear button when search keywords are present.
- Adjust search field width based on the presence of search keywords.

Add ClearSearchKeywords operator to reset search keywords

---

upload.py

fixes #1497
- when asset_data.author_fullName is not present, the error is thrown
- author and fullName should be there, but... if they are not, add-on should handle it

Fix #1497 Scene upload can fail on `key not in subgroup dict`

---

bg_blender.py
upload.py
upload_bg.py

fixes #1501 
- also improves handling of errors from the server when upload data are not correct - Django returns not only {"details": {....} } but sometimes the details can be also just a list. So the error handling function now checks for the type of the error details.

Fix #1501 upload of printable asset type is broken

---

__init__.py
asset_drag_op.py
asset_inspector.py
search.py

fixes #1509
fixes #1504 
Enhance asset handling by supporting "printable" asset type alongside "model" in various components. Update extension draw overrides to only apply in non-background mode for Blender versions 4.2.0 and above.

Fix autothumbnailer and printables upload/download

---

__init__.py
client/networking.go

Fix #1518 Custom proxy settings are not used for the http transpot layer

---

asset_bar_op.py
client/main.go
client/structs.go
global_vars.py
ui.py
ui_panels.py

fixes #1589 
- Client now also download photo_thumbnail ThumbnailMiddleURL aka full thumbnail size
- full photo thumbnail is used in asset popup card, it is shown below the normal thumbnail
- for asset tooltip it is possible to switch between normal thumbnail and photo thumbnail
- either cycle by pressing `[` or `]` over the asset small thumbnail
- or toggle the photo thumbnail by pressing `2`, toggle normal thumbnail by pressing `1`
- both shortcuts are chosen so we could theoretically implement more thumbnails in the future and allow users to cycle/switch between type 1, 2, 3...

Implement #1589 Preview photo thumbnails on the printables

---

append_link.py
asset_drag_op.py
download.py

Works in all areas now, but actively in 3d view and Outliner handles detection of Outliner selections quite nicely, but still throws some error that doesn't influence functionality Cancels in all other views by now
works quite well for materials, objects, printables
This is important also for implementing drag drop from browser as planned. The client should be able simply to run this operator and it should be active when the mouse enters blender window.
TODO: nodes in node editors.

Improve asset drag drop operator:

---

ratings_utils.py

This fixes the complexity rating for these asset types, 
it used the default 0-5 range, but in this case much more is needed.

Fix complexity rating ranges for printable and nodegroup asset tyes

---

upload.py

fixes #1621
- parametry (dimensionX/Y/Z a boundBoxMin/Max//X/Y/X)v adminu povolene i pro printables

FIx #1621 Add dimension and boundBox metadata to Printables upload

---

bl_ui_widgets/bl_ui_button.py
bl_ui_widgets/bl_ui_draw_op.py
overrides.py
unpack_asset_bg.py
utils.py

fixes #1618
- AssetBar search tab's font is defined dynamically as half of its height, but blf.size() does not accept floats in Blender 3.0, so it needs to be converted to int()
- Remove bare prints of exceptions - use traceback or logger.exception() instead because `except Exception as e: print(e)` makes it a nightmare to find the LOC, spent 60+minutes just searching for the place from where the error `integer argument expected, got float` come

Fix #1618 AssetBar's title need to set font size in int in Blender 3.0

---

asset_drag_op.py

fixes #1625 
- oldschool context overrides need to be applied for Blender 3.0 and 3.1

Fix #1625 AssetBar calls to bpy.context.temp_override() breaks in B3.0, B3.1

---

asset_bar_op.py
download.py
ratings.py
ui_panels.py

Prevents asset bar shortcuts (S, R, etc.) from triggering while typing in comment fields and other text inputs. Double letters like "issue" or "RR" were incorrectly triggering Search Similar and Rating dialogs.
Changes:
Renamed last_time_dropdown_active to last_time_overlay_panel_active for better clarity
Added 0.5-second blocking period after popup/text input activity in asset bar shortcut handler
Extended timing mechanism to cover AssetPopupCard, rating dialogs, and comment input fields
Reuses existing timing infrastructure originally designed for category dropdown protection
Result: Users can now type freely in text fields without accidentally triggering shortcuts.

Fix shortcut interference when typing in text input fields

---

utils.py

When running Blender with factory default settings, via `--factory-startup`, factory default preferences are used and user preferences are skipped and not saved (autosave is disabled). However, trying to enable this add-on (which fails, but can be a separate fix) triggers an unexpected save to user preferences, causing the factory startup settings to override the user's. This prevents that.
While doing some testing, I noticed that user preferences are saved even on factory default startup (enabling the add-on seems to fail, but that's a separate issue), which is supposed to ignore and not save user preferences unless the user presses the button. This prevents that from happening, regardless of if the add-on starts up correctly or not.

Skip saving to user preferences on factory startup

---

__init__.py
asset_drag_op.py
ui_panels.py

fixes #1197 
- also reformulate the API key description in the preferences, so it is clear that user do not need to fill it manually or tweak or whatever

Improvement #1197 Clearer text for locked full plan asset

---

upload.py

- scale.Z = 0.999999 would trigger the scale check
- Apply scale on light will not fix the problem
- value will be rounded in Blender GUI, making it hard to find
- now we will round values slightly off 1.0 to 1.0

Fix #1619 Minor scale drifts on point light prevents model upload

---

__init__.py
search.py
test_search.py
ui_panels.py

fixes #1677
- keeps current 'dynamic' and somehow smart sorting as the default
- adds sorting by created, bookmarks, score, complexity, quality

Implement #1677 Add 'Sort by:' to search filters
